name: Feature Request
description: Suggest an improvement or new example
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What should be improved or added?
    validations:
      required: true

  - type: textarea
    id: benefit
    attributes:
      label: Benefit
      description: Why is this useful?
    validations:
      required: true
