# This file is part of the UnleashWP Code Examples.
# Copyright (C) 2025 Benjamin Zekavica
#
# Licensed under the GNU GPL v3 or later.
# See <https://www.gnu.org/licenses/>

name: my-wp-project
type: wordpress
docroot: web
php_version: "8.2"
mariadb_version: "10.11"
router_http_port: "8080"
router_https_port: "8443"
xdebug_enabled: false

web_environment:
  - WORDPRESS_VERSION=6.8